### ISSUE TITLE
Video atlatırken sabit değil değişebilen süreler kullanılabilir.

### ISSUE THREAD

**Issue by toprakozt** [mthnzbk/pisi-player#4]
> Sağ ok: 10sn ileri
> Sol ok: 10sn geri
> Yukarı ok: 1dk ileri
> Aşağı ok: 1dk geri
> Fare tekerleği - yukarı: 1dk ileri
> Fare tekerleği - aşağı: 1dk geri

3 dakikalık klip izlerken 1 dakika/10 saniye ileri/geri sardırmaktansa toplam video süresinin %x'lik kısmı sardırılabilir. Aynı şekilde 2 saatlik bir film izlerken de 1 dakika ileri sarmaktan daha işlevsel bir süre hesaplatılabilir.

**Comment by mthnzbk** [comment]
Yüzdelik kısım değişik sürelerde istenileni vermeyebilir. Misal 2 saatllik film de olsa insan bakışmalarla geçen sahneyi atlamak için sağ oka basınca yüzdelik dilimde ilerleme olsa çok daha fazla ileri sarmış olur. Kısa videolar için de tam zıttı. Daha düşük süre atlaması ile, atlamaması arasında pek fark kalmaz. Ama ayrı kısa yollar eklenerek süre olarak daha fazla ileri geri sarmasını istiyorsanız düşünebilirim.

**Comment by toprakozt** [comment]
Bu sorun genelde video oynatıcılarda karşılaştığım bir sorun. O yüzden bildirmek istedim. 

Öte yandan dediğiniz gibi bazı zamanlar 2 saatlik bir film dahi olsa kısa süreler atlamak isteniyor. Bunun için optimum bir yol bulunabilir diye düşünüyorum. Sağ/sol ok sabit, üst/alt oklar değişken sürelerde videoyu sardırabilir. Dediğiniz gibi `Ctrl + Sağ ok` gibi yeni kombinasyonlarla da halledilebilir.

**Comment by mthnzbk** [comment]
Fazla süre atlama da fare ile slider üzerinde oynama yapılabilir. Video izlerken, ne kadar az tuşa basarsanız o kadar iyi değil mi?
